name: Issues

on:
  issues:
    types: [opened]

jobs:
  issue:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Add issue to project board
      run: |
        gh project item-add 1 --owner Diruptio --url ${{ github.event.issue.html_url }}
        gh project item-edit --id ${{ github.event.issue.id }} --field-id Status --single-select-option-id Issues